### ISSUE TITLE
用ggplot2画图，中文是乱码怎么处理？

### ISSUE THREAD

**Issue by snchrome** [ShichenXie/dstudio#2]
用网上搜的方法，需要root权限安装字库。也不知道root密码。

**Comment by ShichenXie** [comment]
`dt <- data.frame(xa = rnorm(100), ya = rnorm(100))

library(ggplot2)
library(showtext)

showtext_auto()  ## select your fonts automaticly

ggplot(dt, mapping = aes(x = xa, y = ya)) + 
    geom_point() + 
    labs(title = "示例数据", x = "横坐标", y = "纵坐标") 

ggsave("Fonts_text.pdf",height = 5,width = 5) 

showtext_auto(FALSE) ## turn off if no longer needed
`
